### ISSUE TITLE
Without Mask 

### ISSUE THREAD

**Issue by buaadf** [xmeng525/NeAT#1]
Thanks for the great work! Is the method capable without mask?

**Comment by xmeng525** [comment]
Hi,

Thank you for your question. Yes, NeAT is capable of reconstructing open surfaces without a mask. I have just uploaded the configuration file "womask.conf" in the "confs" folder which can be used for this purpose.

As an example, I have already used this configuration file to reconstruct a T-shirt without a coat (MGN/TShirtNoCoat_125611500935128). Feel free to try it out and explore more examples!

![MGN02](https://user-images.githubusercontent.com/25536317/235527109-520e6fc8-c6c9-4a41-a466-ea3407b5fc09.png)

Let me know if you have any further questions or concerns.
