### ISSUE TITLE
incomplete mesh on custom data

### ISSUE THREAD

**Issue by yipingp** [xmeng525/NeAT#5]
When testing on custom data, the mesh is incomplete, but the normals seem correct. 
<img src="https://github.com/xmeng525/NeAT/assets/50096739/66b73731-32fb-4683-97b5-3fc93a81bc63" width=35% height=35%>
<img src="https://github.com/xmeng525/NeAT/assets/50096739/d1e5d832-8173-4613-85ac-e41e1add705d" width=20% height=20%>

And I tested this same data with NeuS, the mesh is complete. Is this problem caused by data preprocessing, parameters, or something else?
<img src="https://github.com/xmeng525/NeAT/assets/50096739/662edf5d-fc58-4f0c-a5ca-60e0a5bf6f2a" width=20% height=20%>

**Comment by xmeng525** [comment]
Hi, would you please let me know the configuration file you used and send me a copy of your input data (if convenient)?Maybe I can try to figure it out.

**Comment by yipingp** [comment]
Thanks for your reply! The configuration file I use is similar to DTU's.
[wmask.txt](https://github.com/xmeng525/NeAT/files/11523770/wmask.txt)
I'm sorry that I may not be able to provide this data. Could you find something or give some guidence through the configuration file?

**Comment by yipingp** [comment]
Hi, this problem seems to be caused by object bounding box setting [here](https://github.com/xmeng525/NeAT/blob/main/models/dataset.py#L94)? 
I keep `object_bbox_min = np.array([-1.01, -1.01, -1.01, 1.0])` and `
        object_bbox_max = np.array([1.01, 1.01, 1.01, 1.0])` only, which is identical to NeuS, and it works.
<img src="https://github.com/xmeng525/NeAT/assets/50096739/57e0d827-22bf-4923-87bc-f682fc812835" width=20% height=20%>

**Comment by xmeng525** [comment]
Good Catch! Let me update this in readme, thank you for pointing this out.
I'll close this issue now. Feel free to contact me if you have any other questions.
