### ISSUE TITLE
输入的图片一定要按特定的顺序么？

### ISSUE THREAD

**Issue by Skypow2012** [xmeng525/NeAT#6]
试了下随机放入图片，会生成像石头一样的形状

**Comment by yuedajiong** [comment]
different options in colmap?

**Comment by yuedajiong** [comment]
![image](https://github.com/xmeng525/NeAT/assets/52232153/bdb31d09-17b0-4f22-b59a-eac59955f2ce)

**Comment by yuedajiong** [comment]
not sequential, but exhaustive, .......................................

**Comment by Skypow2012** [comment]
> different options in colmap?

感谢回复，我后来发现原来每个场景都需要重新训练
